# fly.toml app configuration file generated for rubito on 2023-10-07T09:12:22-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rubito"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
